name: hadi
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_screenutil: ^5.9.3


  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13  


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true


  assets:
    - lib/assets/